name: banner_carousel_odoo
description: "Banner carousel by ODOO"
version: 0.0.1
homepage: 'https://www.manexware.com'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

authors:
  - Manuel Vega Ulloa <manuel.vega@manexware.com>

maintainers:
  - Manuel Vega Ulloa <manuel.vega@manexware.com>